# Database module — inputs.
#
# Naming/tags come from Foundation; network refs from Networking. No credential
# is ever accepted as an input — RDS generates and stores it in Secrets Manager.

variable "name_prefix" {
  description = "Resource-name prefix from Foundation (e.g. rentflow-staging)."
  type        = string
}

variable "tags" {
  description = "Standard tag set from Foundation (common_tags)."
  type        = map(string)
}

# --- Networking ---
variable "vpc_id" {
  description = "VPC ID (from Networking)."
  type        = string
}

variable "subnet_ids" {
  description = "Private database subnet IDs (from Networking private_db_subnet_ids)."
  type        = list(string)
}

variable "allowed_security_group_ids" {
  description = "Security groups allowed to reach PostgreSQL (e.g. the future backend SG). Empty = no ingress."
  type        = list(string)
  default     = []
}

variable "allowed_cidr_blocks" {
  description = "CIDRs allowed to reach PostgreSQL (e.g. a VPN range). Empty = none. Never use 0.0.0.0/0."
  type        = list(string)
  default     = []

  validation {
    condition     = !contains(var.allowed_cidr_blocks, "0.0.0.0/0")
    error_message = "0.0.0.0/0 is not allowed for database ingress."
  }
}

# --- Public access (keep false except for controlled, IP-restricted access) ---
variable "publicly_accessible" {
  description = "Assign the instance a public IP. Keep false except for temporary, CIDR-restricted access (e.g. a developer laptop). Requires the subnet group to use public subnets and matching allowed_cidr_blocks."
  type        = bool
  default     = false
}

# --- Engine / sizing ---
variable "engine_version" {
  description = "PostgreSQL major (or major.minor) version."
  type        = string
  default     = "16"
}

variable "instance_class" {
  description = "RDS instance class. Default is a small Graviton class for staging."
  type        = string
  default     = "db.t4g.micro"
}

variable "allocated_storage" {
  description = "Initial storage (GiB)."
  type        = number
  default     = 20
}

variable "max_allocated_storage" {
  description = "Upper bound for storage autoscaling (GiB). 0 disables autoscaling."
  type        = number
  default     = 100
}

variable "storage_type" {
  description = "EBS storage type."
  type        = string
  default     = "gp3"
}

variable "database_name" {
  description = "Initial database name."
  type        = string
  default     = "rentflow"
}

variable "master_username" {
  description = "Master username. The PASSWORD is generated by RDS and stored in Secrets Manager (never here)."
  type        = string
  default     = "rentflow_admin"
}

# --- Encryption ---
variable "kms_key_arn" {
  description = "Customer-managed KMS key for storage, the master-user secret, and Performance Insights. Null = AWS-managed keys."
  type        = string
  default     = null
}

# --- Availability / backups / protection ---
variable "multi_az" {
  description = "Deploy a standby in a second AZ (recommended for production)."
  type        = bool
  default     = false
}

variable "backup_retention_period" {
  description = "Automated backup retention in days (1-35; >0 keeps backups enabled)."
  type        = number
  default     = 7

  validation {
    condition     = var.backup_retention_period >= 1 && var.backup_retention_period <= 35
    error_message = "backup_retention_period must be between 1 and 35 (backups must stay enabled)."
  }
}

variable "deletion_protection" {
  description = "Prevent accidental deletion of the instance."
  type        = bool
  default     = true
}

variable "skip_final_snapshot" {
  description = "Skip the final snapshot on destroy. Keep false for production safety."
  type        = bool
  default     = false
}

# --- Observability ---
variable "performance_insights_enabled" {
  description = "Enable Performance Insights."
  type        = bool
  default     = false
}

variable "performance_insights_retention_period" {
  description = "Performance Insights retention (days). 7 is free tier."
  type        = number
  default     = 7
}

variable "apply_immediately" {
  description = "Apply changes immediately instead of in the maintenance window."
  type        = bool
  default     = false
}
